/**
 * @file verification_agent.ts
 * @description The "Auditor" agent that double-checks AI headnotes against raw source text.
 * @module backend/src/lib/agents
 */

import OpenAI from "openai";
import { LLM_MODELS } from "../ai";

const openai = new OpenAI({
    baseURL: "https://openrouter.ai/api/v1",
    apiKey: process.env.OPENROUTER_API_KEY,
    defaultHeaders: {
        "HTTP-Referer": process.env.SITE_URL || "http://localhost:3000",
        "X-Title": process.env.SITE_NAME || "PolyPact",
    },
});

export async function auditHeadnote(rawText: string, generatedHeadnote: string): Promise<string> {
    try {
        const systemPrompt = `You are the PolyPact Legal Auditor.
        Your JOB is to prevent hallucinations.
        
        INPUT:
        1. RAW SOURCE TEXT (The ground truth).
        2. DRAFT HEADNOTE (Generated by a junior lawyer).

        TASK:
        Verify that the content in the Draft is supported by the Source.
        
        RULES:
        - If the Draft claims facts, sections, or holdings NOT in the Source, DELETE them.
        - STRUCTURE: You MUST return a JSON object with exactly these 4 keys: "Facts", "Held", "Ratio", "Judgment".
        - MAPPING FOR NON-JUDGMENTS (Statutes/Rules):
            - If it's a Statute/Rule, use "Facts" for 'Source/Background/Context'.
            - Use "Ratio" for 'Rule definition/Legal Principle/Interpretation'.
            - Use "Held" for 'Applicability/Procedure/Action'.
            - Use "Judgment" for 'Summary/Conclusion'.
        - If a section has NO supported information, use "Data not available in official source" instead of an empty string.
        - Ensure every claim is grounded in the provided Source text.
        
        OUTPUT:
        Return ONLY the CLEANED, VERIFIED JSON object. No conversational text.
        `;

        const completion = await openai.chat.completions.create({
            model: LLM_MODELS.GENERAL, // Using a smart reasoning model (Cydonia/Flash)
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: `SOURCE:\n${rawText.substring(0, 15000)}\n\nDRAFT:\n${generatedHeadnote}` }
            ],
            temperature: 0, // Zero temp for strictness
        });

        return completion.choices[0].message.content || generatedHeadnote;

    } catch (error) {
        console.warn("Audit failed, returning original draft", error);
        return generatedHeadnote;
    }
}
